### ISSUE TITLE
Nuxt.js is not detected

### ISSUE THREAD

**Issue by koresar** [johnmichel/Library-Detector-for-Chrome#148] opened 2019-10-24 00:39 UTC
Very weird.
Open this website: https://nuxtjs.org/
The Nuxt.js is not detected. Although the `window.$nuxt` exists.

**Comment by wellingguzman** [comment] 2019-10-26 12:10
I noticed that too, it's not a bug, but the version on the chrome store is outdated (5.2.0), and the test for Nuxt.js was added in [v5.3.0](https://github.com/johnmichel/Library-Detector-for-Chrome/releases/tag/v5.3.0)

**Comment by johnmichel** [comment] 2019-12-19 15:49
I've uploaded `5.6.0` to the Chrome Web Store that should include support for `Nuxt.js`.  It's currently under review for publishing.

**Comment by johnmichel** [comment] 2019-12-23 14:06
This is now fixed in the published version that's available from the Chrome Web Store

**Closed by johnmichel** 2019-12-23 14:06 UTC
